<?php
/**
 * @category    Fishpig
 * @package     Fishpig_Wordpress
 * @license     http://fishpig.co.uk/license.txt
 * @author      Ben Tideswell <help@fishpig.co.uk>
 */
?>
<?php 

$postID = $this->getData('post');
$categoryID = $this->getData('category');

$posts = $this->getPosts();
$posts->addCategoryAndPostIdFilter($postID,$categoryID,$operator = 'OR');

if (count($posts) > 0) { 

	foreach($posts as $post) {
		if($featuredImage = $post->getFeaturedImage()){
			$image = $featuredImage->getFullSizeImage();
		} else {
			$image = $url.'images/placeholder-revista.jpg';
		} 
		?>
		<div class="block block-blog article">
			<div class="block-content">
				<li class="item" style="background-image: url(<?php echo $image; ?>)">
					<a href="<?php echo $post->getPermalink() ?>" title="<?php echo $post->getPostTitle() ?>"><?php echo $post->getPostTitle(); ?></a>
				</li>
			</div>
		</div>
	<?php }
}
?>