<?php
/**
 * @category    Fishpig
 * @package     Fishpig_Wordpress
 * @license     http://fishpig.co.uk/license.txt
 * @author      Ben Tideswell <help@fishpig.co.uk>
 */
?>
<?php $posts = $this->getPosts() ?>
<?php if ($posts && count($posts) > 0): ?>
	<div class="yarpp-related row">
		<?php if ($this->isThumbnailView()): ?>
			<div class="fhead">
			    <a href="/revista"><h2 class="subtitle"><?php echo $this->__($this->getThumbnailsHeading()) ?></h2></a>
			</div>
			<div class="yarpp-thumbnails-horizontal posts-grid">
				<?php foreach($posts as $post): 

					//$url = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);
					
					if($featuredImage = $this->getThumbnailImage($post)){
						$image = $this->getThumbnailImage($post);
					} else {
						//$image = $url.'images/placeholder-revista.jpg';
						$image = $this->getSkinUrl('images/placeholder-revista.jpg');
					}?>

					<div class="col33 col">
						<li class="item" style="background-image: url(<?php echo $image; ?>)">
							<a href="<?php echo $post->getPermalink() ?>" title="<?php echo $this->escapeHtml($post->getPostTitle()) ?>"><?php echo $this->escapeHtml($post->getPostTitle()) ?></a>
						</li>
					</div>
				<?php endforeach; ?>
				<div class="clearfix"></div>
			</div>
		<?php else: ?>
			<?php echo $this->getBeforeBlockHtml() ?>
			<?php foreach($posts as $post): ?>
				<?php echo $this->getBeforeEntryHtml() ?>
					<a href="<?php echo $post->getPermalink() ?>" title="<?php echo $this->escapeHtml($post->getPostTitle()) ?>"><?php echo $this->escapeHtml($post->getPostTitle()) ?></a>
					<?php if ($this->canShowExcerpt()): ?>
						<?php echo $this->getBeforeExcerptHtml() ?><?php echo $this->getPostExcerpt($post) ?><?php echo $this->getAfterExcerptHtml() ?>
					<?php endif; ?>
				<?php echo $this->getAfterEntryHtml() ?>
			<?php endforeach; ?>
			<?php echo $this->getAfterBlockHtml() ?>
		<?php endif; ?>
	</div>
<?php endif; ?>