<?php
/*
 * New product Extension Developed by Magehit
 */
?>
<?php

$_item = $this->getStoreconfig();
$enable = $_item['enabled'];
$title = $_item['horizontal_carousels_setting_title'];
$limit = $_item['horizontal_carousels_setting_limit'];
$slide_itemsonpage = $_item['horizontal_carousels_setting_slide_itemsonpage'];
$slide_auto = $_item['horizontal_carousels_setting_slide_auto'];
	if($slide_auto == 1) $slide_auto = 'true'; else $slide_auto = 'false';
$slide_navigation = $_item['horizontal_carousels_setting_slide_navigation'];
	if($slide_navigation == 1) $slide_navigation = 'true'; else $slide_navigation = 'false';

$newproducts = $this->getNewProducts($limit);
?>
<?php if ($enable): ?>
    <div class="newproducts">
        <div class="nphead">
            <h2 class="subtitle"><?php echo $this->__($title); ?></h2>
        </div>
        <?php if ($newproducts->count()>0): ?>
            <div id="owl-newproducts" class="owl-carousel product-grid">
                    <?php foreach ($newproducts as $_product) : ?>
                            <div class="item">
                                <a href="<?php echo $this->getUrl($_product->getUrlPath()) ?>" >
                                    <span>
                                        <img class="lazyOwl" data-src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(260) ?>" alt="<?php echo $this->htmlEscape($_product->getName()) ?>" title="<?php echo $this->htmlEscape($_product->getName()) ?>" />
                                    </span>
                                </a>
                                <h3 class="product-name">
                                    <a href="<?php echo $this->getUrl($_product->getUrlPath()) ?>" ><?php echo $_product->getName(); ?>
                                    </a>                   
                                </h3>
                                <span class="price-con">
								<?php	
                                    $finalprice = Mage::helper('core')->currency($_product->getFinalPrice(),true,false);
                                    $price = Mage::helper('core')->currency($_product->getPrice(),true,false);
                                    if ($finalprice != $price){
                                        ?>
                                        <div class="price-box">                     
                                            <p class="old-price">
                                                <span class="price" id="old-price-1401">
                                                    <?php echo $price; ?>                
                                                </span>
                                            </p>

                                            <span class="labelS ofertaprod"></span>
                                            <p class="special-price">
                                                <span class="price-label">Special Price</span>
                                                <span class="price" id="product-price-1401">
                                                    <?php echo $finalprice; ?>                 
                                                </span>
                                            </p>
                                        </div>
                                        <?php
                                    } else {
                                        echo $finalprice;
                                    }					
									
								?>
								</span>
                            </div>
                <?php endforeach; ?>
            </div>
        <?php else: ?>
            <div class="show-msg">
                <?php echo $this->__("There are no new products."); ?> 
            </div>
        <?php endif; ?>
    </div>
    
<?php endif; ?>
<script type="text/javascript">
	var $fp = jQuery.noConflict();
    $fp(document).ready(function() {
      $fp("#owl-newproducts").owlCarousel({
        items : <?php echo $slide_itemsonpage ?>,
        lazyLoad : true,
		autoPlay : <?php echo $slide_auto ?>,
        navigation : <?php echo $slide_navigation ?>
      }); 
     
    });
</script>



