<div class="footer-subscribe">
	<div class="title">Fique por dentro!</div>
	<form action="<?php echo $this->getFormActionUrl() ?>" method="post" id="footer-newsletter-validate-detail">
		<p>Cadastre-se para receber nossas novidades</p>
		<button type="submit" title="<?php echo $this->__('Subscribe') ?>" class="button">
			<span><span>EU QUERO</span></span></button>
		<div class="input-box">
		<input type="text" name="email" id="footer-newsletter"
		       title="<?php echo $this->__('Sign up for our newsletter') ?>"
		       class="input-text required-entry validate-email"
		       value="Digite seu e-mail aqui"
		       onfocus="if ( this.value == '<?php echo $this->__('Type your email address here') ?>' ) { this.value = '' }"
		       onblur="if ( this.value == '' ) { this.value = '<?php echo $this->__('Type your email address here') ?>' }"
			/>
		</div>
		<div class="clear"></div>
	</form>
	<script type="text/javascript">
		//<![CDATA[
		var newsletterSubscriberFormDetail = new VarienForm('footer-newsletter-validate-detail');
		//]]>
	</script>
</div>