<?php
/**
 * @category    Fishpig
 * @package     Fishpig_Wordpress
 * @license     http://fishpig.co.uk/license.txt
 * @author      Ben Tideswell <help@fishpig.co.uk>
 */
?>
<div class="col30 col revista">
<?php if (($posts = $this->getPostCollection()) !== false): ?>
<?php if (count($posts) > 0): ?>
	<div class="block block-blog block-recent-posts">
		<div class="block-title">
			<strong><span>Revista</span></strong>
		</div>
		<div class="block-content">
			<ul id="">
			<?php foreach($posts as $post): 
				if($featuredImage = $post->getFeaturedImage()){
						$image = $featuredImage->getFullSizeImage();
					} else {
						$image = $this->getSkinUrl('images/placeholder-revista.jpg');
					}?>
				<li class="item" style="background-image: url(<?php echo $image; ?>)">
					<a href="<?php echo $post->getPermalink() ?>" title="<?php echo $this->htmlEscape($post->getPostTitle()) ?>"><?php echo $this->htmlEscape($post->getPostTitle()) ?></a>
				</li>
			<?php endforeach; ?>
			</ul>
		</div>
	</div>
<?php endif; ?>
<?php endif; ?>
</div>