<?php
/**
 * @category    Fishpig
 * @package     Fishpig_Wordpress
 * @license     http://fishpig.co.uk/license.txt
 * @author      Ben Tideswell <help@fishpig.co.uk>
 */
?>
<?php $posts = $this->getPosts();

$url = Mage::getBaseUrl();

if(has_post_thumbnail()){
	$image = the_post_thumbnail();
} else {
	$image = 'plaholder-revista.jpg';
}
 ?>
<?php if (count($posts) > 0): ?>
	<div class="block block-blog block-related-posts">
		<?php if ($title = $this->getTitle()): ?>
			<div class="block-title">
				<strong><span><?php echo $this->__($title) ?></span></strong>
			</div>
		<?php endif; ?>
		<div class="block-content">
			<ul id="<?php echo $this->getListId() ?>">
			<?php foreach($posts as $post): ?>
				<li class="item" style="background-image: url(<?php echo $url."skin/frontend/alab16/default/images/".$image; ?>)">
					<a href="<?php echo $post->getPermalink() ?>" title="<?php echo $this->htmlEscape($post->getPostTitle()) ?>"><?php echo $this->htmlEscape($post->getPostTitle()) ?></a>
				</li>
			<?php endforeach; ?>
			</ul>
			<script type="text/javascript">decorateList('<?php echo $this->getListId() ?>')</script>
		</div>
	</div>
<?php endif; ?>