<?php
/**
 * @category    Fishpig
 * @package     Fishpig_Wordpress
 * @license     http://fishpig.co.uk/license.txt
 * @author      Ben Tideswell <help@fishpig.co.uk>
 */
?>
<?php if ($post = $this->getPost()): ?>
	<?php if($featuredImage = $post->getFeaturedImage()){
		$image = $featuredImage->getFullSizeImage(); ?>
		<div class="post-image"><img src="<?php echo $image; ?>"></div>
	<?php } ?>	
	<?php echo $this->getBeforePostContentHtml() ?>
	<div class="page-title post-title">
		<h2><?php echo $this->escapeHtml($post->getPostTitle()) ?></h2>
	</div>
	<div class="post-view">		
		<div class="post-entry entry std">
			<?php if ($post->isViewableForVisitor()): ?>
				<?php if ($featuredImage = $post->getFeaturedImage()): ?>
					<div class="featured-image left">
						<img src="<?php echo $featuredImage->getAvailableImage() ?>" alt="<?php echo $this->escapeHtml($post->getPostTitle()) ?>"/>
					</div>
				<?php endif; ?>
				<?php echo $post->getPostContent() ?>
			<?php else: ?>
				<?php echo $this->getPasswordProtectHtml() ?>
			<?php endif; ?>
		</div>
	</div>
<?php endif; ?>