<?php
$rootId = 366;
$categories = Mage::getModel('catalog/category')->getCollection()
    ->addAttributeToSelect('*')
    ->addAttributeToFilter('parent_id', $rootId)
    ->setOrder('position')
    ->addAttributeToFilter('is_active', 1);

$_helper = $this->helper('catalog/output'); 
?>
<?php if ($categories->count() > 0) : ?>

<ul>
    <?php foreach ($categories as $category) : ?>
       <li>
           <div class="name">
              <a href="<?php echo $category->getUrl()?>" title="<?php echo $this->escapeHtml($category->getName())?>"><?php echo $category->getName()?></a>
           </div>
           <div class="image">
               <?php if ($category->getImageUrl()) :?>
                   <img src="<?php echo $category->getImageUrl()?>" alt="<?php echo $this->escapeHtml($category->getName())?>" />
               <?php endif;?>
           </div>
           <div class="description">
               <?php echo $_helper->categoryAttribute($category, $category->getDescription(), 'description') ?>
           </div>
           <img class="lazyOwl" data-src="http://ambientelab.local.com.br/media/catalog/product/cache/1/small_image/260x/9df78eab33525d08d6e5fb8d27136e95/1/7/1793.jpg" alt="Mesa Centro Bronze " title="Mesa Centro Bronze ">
           <div class="ccarousel">
            <div id="owl-ccarouselproducts" class="owl-carousel">
           <?php 
            $id = $category->getID();
            $cproducts = Mage::getModel('catalog/category')->load($id)
             ->getProductCollection()
             ->addAttributeToSelect('*') 
             ->addAttributeToFilter('status', 1)
             ->addAttributeToFilter('visibility', 4); 
             foreach ($cproducts as $cproduct) { 
              ?>
                <div class="item">
                   <a href="<?php echo $cproduct->getUrlPath(); ?>" >
                      <span>
                          <img class="lazyOwl" src="<?php echo $this->helper('catalog/image')->init($cproduct, 'small_image')->resize(260) ?>" alt="<?php echo $cproduct->getName() ?>" title="<?php echo $cproduct->getName() ?>" />
                      </span>
                  </a>
                  <h3 class="product-name">
                      <a href="<?php echo $cproduct->getUrlPath() ?>" ><?php echo $cproduct->getName(); ?>
                      </a>                   
                  </h3>
                  <span class="price-con">
                    <?php                 
                       echo Mage::helper('core')->currency($cproduct->getFinalPrice(),true,false);
                    ?>
                  </span> 
                </div>
             <?php } ?>
            </div>
            </div>
       </li>
    <?php endforeach;?>
</ul>
<?php endif;?>
<script type="text/javascript">
  var $fp = jQuery.noConflict();
    $fp(document).ready(function() {
      $fp("#owl-ccarouselproducts").owlCarousel({
        items : 5,
        lazyLoad : true,
    autoPlay : false,
        navigation : false
      }); 
     
    });
</script>