<?php
/*
 * Featured product Extension Developed by Magehit
 */
?>
<?php
$products = Mage::getModel('catalog/product')->getCollection();
$products->addAttributeToSelect('*');
$products->addAttributeToFilter('status', 1);
$products->addAttributeToSelect('is_featured');
$products->addFieldToFilter(array(
			array('attribute' => 'is_featured', 'eq' => true),
		));
//var_dump($products->getData());die;
$prodIds = $products->getAllIds();
$ftotalproduct = count($prodIds);
$_item = $this->getStoreconfig();
$enable = $_item['enabled'];
$title = $_item['vertical_carousels_setting_title'];
$limit = $_item['vertical_carousels_setting_limit'];
$slide_itemsonpage = $_item['vertical_carousels_setting_slide_itemsonpage'];
$slide_auto = $_item['vertical_carousels_setting_slide_auto'];
	if($slide_auto == 1) $slide_auto = 'true'; else $slide_auto = 'false';
$slide_navigation = $_item['vertical_carousels_setting_slide_navigation'];
	if($slide_navigation == 1) $slide_navigation = 'true'; else $slide_navigation = 'false';

?>
<?php if ($enable): ?>
    <div class="clearfix"></div>
    <div class="featured sidebar">
        <div class="fhead">
            <h2 class="subtitle ver_subtitle"><?php echo $this->__($title); ?></h2>
        </div>
        <?php if ($ftotalproduct): ?>
            <div id="vertical-featuredproducts">
                    <?php $count = 1; ?>
                    <?php foreach ($products as $_product) : ?>
                        <?php if ($count <= $limit): ?>
                            <div class="item">
                                <a href="<?php echo $this->getUrl($_product->getUrlPath()) ?>" >
                                    <span>
                                        <img class="lazyOwl" src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(260) ?>" alt="<?php echo $this->htmlEscape($_product->getName()) ?>" title="<?php echo $this->htmlEscape($_product->getName()) ?>" />
                                    </span>
                                </a>
                                <h3 class="product-name">
                                    <a href="<?php echo $this->getUrl($_product->getUrlPath()) ?>" ><?php echo $_product->getName(); ?>
                                    </a>                   
                                </h3>
                                <span class="price-con">
								<?php   
                                    $finalprice = Mage::helper('core')->currency($_product->getFinalPrice(),true,false);
                                    $price = Mage::helper('core')->currency($_product->getPrice(),true,false);
                                    if ($finalprice != $price){
                                        ?>
                                        <div class="price-box">                     
                                            <p class="old-price">
                                                <span class="price" id="old-price-1401">
                                                    <?php echo $price; ?>                
                                                </span>
                                            </p>

                                            <span class="labelS ofertaprod"></span>
                                            <p class="special-price">
                                                <span class="price-label">Special Price</span>
                                                <span class="price" id="product-price-1401">
                                                    <?php echo $finalprice; ?>                 
                                                </span>
                                            </p>
                                        </div>
                                        <?php
                                    } else {
                                        echo $finalprice;
                                    }                   
                                    
                                ?>
								</span>
                            </div>
                    <?php endif; ?>
                    <?php $count++ ?>
                <?php endforeach; ?>
            </div>
    </div>
    <?php else: ?>
        <div class="show-msg">
            <?php echo $this->__("Não há produtos em destaque."); ?> 
        </div>
    <?php endif; ?>
<?php endif; ?>