<?php
/**
 * @category    Fishpig
 * @package     Fishpig_Wordpress
 * @license     http://fishpig.co.uk/license.txt
 * @author      Ben Tideswell <help@fishpig.co.uk>
 */
?>
<?php $post = $this->getPost(); ?>
<!-- <div class="post-list-item">
	<?php if($featuredImage = $post->getFeaturedImage()){
	$image = $featuredImage->getFullSizeImage(); ?>
	<div class="post-image"><img src="<?php echo $image; ?>"></div>
	<?php } ?>	
	<?php echo $this->getAfterPostContentHtml() ?>
	<h2><a href="<?php echo $post->getPermalink() ?>" title="<?php echo $this->escapeHtml($post->getPostTitle()) ?>"><?php echo $this->escapeHtml($post->getPostTitle()) ?></a></h2>
	<?php echo $this->getBeforePostContentHtml() ?>
	<div class="post-entry entry">
		<?php if ($post->isViewableForVisitor()): ?>
			<?php if ($this->displayExcerptInFeed() || $post->hasMoreTag()): ?>
				<?php 
					/**
					* You can pass the number of words you want the excerpt to be shortened to like so
					* The below code will only show the first 50 words of the excerpt
					* <?php echo $post->getPostExcerpt(50) ?>
					*
					**/ 
				?>
				<?php echo $post->getPostExcerpt() ?>
			<?php else: ?>
				<?php echo $post->getPostContent() ?>
			<?php endif; ?>
		<?php else: ?>
			<?php echo $this->getPasswordProtectHtml($post) ?>
		<?php endif; ?>
	</div>
</div> -->
<?php 	
		$image = $this->getSkinUrl('images/placeholder-revista.jpg');
		if($featuredImage = $post->getFeaturedImage()){$image = $featuredImage->getFullSizeImage();} 			
		?>
<div class="col col50">
<li class="item<?php if ($post->isSticky()): ?> featured is-sticky<?php endif; ?> <?php echo $post->getPostFormat() ?>" style="background-image: url(<?php echo $image; ?>)">
	<a href="<?php echo $post->getPermalink() ?>" title="<?php echo $this->escapeHtml($post->getPostTitle()) ?>">
		<?php echo $this->escapeHtml($post->getPostTitle()) ?>	
	</a>
</li>
</div>
